name: hexal_engine
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^2.9.0

dependencies:
  equatable: ^1.2.0

dev_dependencies:
  test: ^1.15.0
  effective_dart: ^1.2.0
